### ISSUE TITLE
TypeError: init() missing 2 required positional arguments: 'format' and 'fields'

### ISSUE THREAD

**Issue by Yaoying-1** [yulijia/SnapCCESS#1]
Hello, when I tried to reproduce the "an_example_of_generate_embedding_using_SnapCCESS_python_version" code, I encountered an error:
Traceback (most recent call last):
File "/home/september/PycharmProjects/SnapCCESS/snapccess-py/snapccess/loaddata.py", line 58, in
train_transformed_dataset = TabularDataset(train_data)
TypeError: init() missing 2 required positional arguments: 'format' and 'fields'
Previously, you mentioned the TabularDataset class from "util.py". However, I couldn't find the TabularDataset class in the "util.py" file. I am referring to the TabularDataset class from "torchtext.data.dataset". How can I solve this issue? Can you provide the complete code? Thank you very much!

**Comment by yulijia** [comment]
Hi @Yaoying-1 

I updated the python notebook, please check the latest version of example. `TabularDataset` is a useless function, I already removed it in the notebook and package.
